import { PageShell } from "../components/SiteShell";

const timeline=[
  ["2022—NOW","Vice President · Product Innovation & AI Solutions","Iorta Technology Solutions · Chennai","Lead product strategy, lifecycle management, pre-sales, RFPs, solution and integration architecture, AI governance, PMO oversight, requirements alignment, UAT readiness and release planning across insurance, banking and NBFC programmes."],
  ["2017—2022","Founder & Innovator","Bank X · UK & Europe","Conceptualised an open-banking platform, directed pre-seed prototyping and UI design, presented to investors, built user communities and validated the proposition through focus groups."],
  ["EARLIER","Banking and client-management roles","Yes Bank · Standard Chartered · RBS / ABN AMRO · Citi","Managed banking relationships and commercial outcomes before moving into product, technology and transformation leadership."],
];
export default function AboutPage(){return <PageShell>
  <section className="page-hero about-hero"><span className="kicker">BHANU HARISH BANDREDDY</span><h1>Technology executive specialising in product innovation, solution architecture and <em>AI-led transformation.</em></h1><p>Based in Chennai, I bring more than fifteen years across global financial services, technology, entrepreneurship and applied AI, with delivery experience across East Africa, Malaysia, Thailand, the Philippines and Vietnam.</p></section>
  <section className="about-statement"><span className="section-index">EXECUTIVE PROFILE</span><blockquote>I convert enterprise transformation priorities into governed products, architectures and delivery programmes.</blockquote><div><p>My current remit extends beyond a standard VP Product mandate. I support delivery costing, RFPs and technical discussions; own market research, roadmap and prioritisation; drive requirements and solution mapping; and align cross-functional teams through implementation.</p><p>I established and manage an AI Centre of Excellence covering solution governance, resource allocation and PMO functions. I also work hands-on with Claude, Gemini, OpenAI, LangChain, Hugging Face, ChromaDB and QLoRA-based model customisation for prototypes and domain-specific AI capabilities.</p></div></section>
  <section className="career-evidence"><article><b>5 markets</b><p>Architected and shipped a single sales CRM base product across East Africa, Malaysia, Thailand, the Philippines and Vietnam.</p></article><article><b>60%</b><p>Improvement in user engagement reported from targeted AI deployment under the AI Centre of Excellence.</p></article><article><b>End-to-end</b><p>Accountability spanning pre-sales, product ownership, solution design, hands-on build, delivery governance and AI leadership.</p></article></section>
  <section className="timeline"><span className="section-index">EXPERIENCE</span>{timeline.map(([date,role,org,text])=><article key={date}><span>{date}</span><div><h2>{role}</h2><b>{org}</b><p>{text}</p></div></article>)}</section>
  <section className="expertise"><div><span className="section-index">CORE COMPETENCIES</span><h2>Strategic vision.<br/>Technical execution.<br/>Enterprise governance.</h2></div><div className="tag-cloud">{["AI strategy and digital transformation","Product innovation and lifecycle management","Solution architecture and system design","Cross-functional leadership","Stakeholder and board engagement","International market development","Operational and financial oversight","AI Centre of Excellence","CRM / ERP transformation","AWS / GCP","OpenAI / Claude / Gemini","LangChain / Hugging Face / ChromaDB"].map(x=><span key={x}>{x}</span>)}</div></section>
</PageShell>}
